# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: devise_pam_authenticatable2 8.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "devise_pam_authenticatable2".freeze
  s.version = "8.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["James Wilson".freeze, "Alexander Kaftan".freeze]
  s.date = "2018-01-17"
  s.description = "For authenticating against PAM (Pluggable Authentication Modules)".freeze
  s.email = "devkral@web.de".freeze
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "devise_pam_authenticatable2.gemspec",
    "lib/devise_pam_authenticatable.rb",
    "lib/devise_pam_authenticatable/model.rb",
    "lib/devise_pam_authenticatable/strategy.rb",
    "lib/devise_pam_authenticatable2.rb"
  ]
  s.homepage = "http://github.com/devkral/devise_pam_authenticatable2".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.13".freeze
  s.summary = "Devise PAM authentication module using rpam2".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<devise>.freeze, [">= 4.0.0"])
      s.add_runtime_dependency(%q<rpam2>.freeze, ["~> 3.0"])
    else
      s.add_dependency(%q<devise>.freeze, [">= 4.0.0"])
      s.add_dependency(%q<rpam2>.freeze, ["~> 3.0"])
    end
  else
    s.add_dependency(%q<devise>.freeze, [">= 4.0.0"])
    s.add_dependency(%q<rpam2>.freeze, ["~> 3.0"])
  end
end

